/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module \16-stage-shift  (
  input [4:0] \char-in ,
  input \shift-clk ,
  input \display-en ,
  input \glbl-rst ,
  output [4:0] st0,
  output [4:0] st1,
  output [4:0] st2,
  output [4:0] st3,
  output [4:0] st4,
  output [4:0] st5,
  output [4:0] st6,
  output [4:0] st7,
  output [4:0] st8,
  output [4:0] st9,
  output [4:0] st10,
  output [4:0] st11,
  output [4:0] st12,
  output [4:0] st13,
  output [4:0] st14,
  output [4:0] st15
);
  wire [4:0] s0;
  wire [4:0] st0_temp;
  wire [4:0] s1;
  wire [4:0] st1_temp;
  wire [4:0] s2;
  wire [4:0] st2_temp;
  wire [4:0] s3;
  wire [4:0] st3_temp;
  wire [4:0] s4;
  wire [4:0] st4_temp;
  wire [4:0] s5;
  wire [4:0] st5_temp;
  wire [4:0] s6;
  wire [4:0] st6_temp;
  wire [4:0] s7;
  wire [4:0] st7_temp;
  wire [4:0] s8;
  wire [4:0] st8_temp;
  wire [4:0] s9;
  wire [4:0] st9_temp;
  wire [4:0] s10;
  wire [4:0] st10_temp;
  wire [4:0] s11;
  wire [4:0] st11_temp;
  wire [4:0] s12;
  wire [4:0] st12_temp;
  wire [4:0] s13;
  wire [4:0] st13_temp;
  wire [4:0] s14;
  wire [4:0] st14_temp;
  wire [4:0] s15;
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i0 (
    .sel( \glbl-rst  ),
    .in_0( \char-in  ),
    .in_1( 5'b11111 ),
    .out( s0 )
  );
  // stage-reg-0
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i1 (
    .D( s0 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st0_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i2 (
    .sel( \glbl-rst  ),
    .in_0( st0_temp ),
    .in_1( 5'b11111 ),
    .out( s1 )
  );
  // stage-reg-1
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i3 (
    .D( s1 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st1_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i4 (
    .sel( \glbl-rst  ),
    .in_0( st1_temp ),
    .in_1( 5'b11111 ),
    .out( s2 )
  );
  // stage-reg-2
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i5 (
    .D( s2 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st2_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i6 (
    .sel( \glbl-rst  ),
    .in_0( st2_temp ),
    .in_1( 5'b11111 ),
    .out( s3 )
  );
  // stage-reg-3
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i7 (
    .D( s3 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st3_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i8 (
    .sel( \glbl-rst  ),
    .in_0( st3_temp ),
    .in_1( 5'b11111 ),
    .out( s4 )
  );
  // stage-reg-4
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i9 (
    .D( s4 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st4_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i10 (
    .sel( \glbl-rst  ),
    .in_0( st4_temp ),
    .in_1( 5'b11111 ),
    .out( s5 )
  );
  // stage-reg-5
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i11 (
    .D( s5 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st5_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i12 (
    .sel( \glbl-rst  ),
    .in_0( st5_temp ),
    .in_1( 5'b11111 ),
    .out( s6 )
  );
  // stage-reg-6
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i13 (
    .D( s6 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st6_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i14 (
    .sel( \glbl-rst  ),
    .in_0( st6_temp ),
    .in_1( 5'b11111 ),
    .out( s7 )
  );
  // stage-reg-7
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i15 (
    .D( s7 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st7_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i16 (
    .sel( \glbl-rst  ),
    .in_0( st7_temp ),
    .in_1( 5'b11111 ),
    .out( s8 )
  );
  // stage-reg-8
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i17 (
    .D( s8 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st8_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i18 (
    .sel( \glbl-rst  ),
    .in_0( st8_temp ),
    .in_1( 5'b11111 ),
    .out( s9 )
  );
  // stage-reg-9
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i19 (
    .D( s9 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st9_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i20 (
    .sel( \glbl-rst  ),
    .in_0( st9_temp ),
    .in_1( 5'b11111 ),
    .out( s10 )
  );
  // stage-reg-10
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i21 (
    .D( s10 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st10_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i22 (
    .sel( \glbl-rst  ),
    .in_0( st10_temp ),
    .in_1( 5'b11111 ),
    .out( s11 )
  );
  // stage-reg-11
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i23 (
    .D( s11 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st11_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i24 (
    .sel( \glbl-rst  ),
    .in_0( st11_temp ),
    .in_1( 5'b11111 ),
    .out( s12 )
  );
  // stage-reg-12
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i25 (
    .D( s12 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st12_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i26 (
    .sel( \glbl-rst  ),
    .in_0( st12_temp ),
    .in_1( 5'b11111 ),
    .out( s13 )
  );
  // stage-reg-13
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i27 (
    .D( s13 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st13_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i28 (
    .sel( \glbl-rst  ),
    .in_0( st13_temp ),
    .in_1( 5'b11111 ),
    .out( s14 )
  );
  // stage-reg-14
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i29 (
    .D( s14 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st14_temp )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i30 (
    .sel( \glbl-rst  ),
    .in_0( st14_temp ),
    .in_1( 5'b11111 ),
    .out( s15 )
  );
  // stage-reg-15
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i31 (
    .D( s15 ),
    .C( \shift-clk  ),
    .en( \display-en  ),
    .Q( st15 )
  );
  assign st0 = st0_temp;
  assign st1 = st1_temp;
  assign st2 = st2_temp;
  assign st3 = st3_temp;
  assign st4 = st4_temp;
  assign st5 = st5_temp;
  assign st6 = st6_temp;
  assign st7 = st7_temp;
  assign st8 = st8_temp;
  assign st9 = st9_temp;
  assign st10 = st10_temp;
  assign st11 = st11_temp;
  assign st12 = st12_temp;
  assign st13 = st13_temp;
  assign st14 = st14_temp;
endmodule
