/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module single_channel_IAE (
  input \enable-bit_(1bit) ,
  input [7:0] WEIGHT,
  input \glbl-loop-clk ,
  input \glbl-inference-state ,
  input \glbl-reset ,
  output [16:0] \accum-class-score 
);
  wire [7:0] s0;
  wire [7:0] s1;
  wire s2;
  wire [16:0] s3;
  wire [16:0] \accum-class-score_temp ;
  wire [16:0] s4;
  wire [16:0] s5;
  assign s0[0] = \enable-bit_(1bit) ;
  assign s0[1] = \enable-bit_(1bit) ;
  assign s0[2] = \enable-bit_(1bit) ;
  assign s0[3] = \enable-bit_(1bit) ;
  assign s0[4] = \enable-bit_(1bit) ;
  assign s0[5] = \enable-bit_(1bit) ;
  assign s0[6] = \enable-bit_(1bit) ;
  assign s0[7] = \enable-bit_(1bit) ;
  assign s1 = (s0 & WEIGHT);
  assign s2 = s1[7];
  assign s3[7:0] = s1;
  assign s3[8] = s2;
  assign s3[9] = s2;
  assign s3[10] = s2;
  assign s3[11] = s2;
  assign s3[12] = s2;
  assign s3[13] = s2;
  assign s3[14] = s2;
  assign s3[15] = s2;
  assign s3[16] = s2;
  // 17bit RCA
  DIG_Add #(
    .Bits(17)
  )
  DIG_Add_i0 (
    .a( s3 ),
    .b( \accum-class-score_temp  ),
    .c_i( 1'b0 ),
    .s( s4 )
  );
  // 17bit accum. reg.
  DIG_Register_BUS #(
    .Bits(17)
  )
  DIG_Register_BUS_i1 (
    .D( s5 ),
    .C( \glbl-loop-clk  ),
    .en( \glbl-inference-state  ),
    .Q( \accum-class-score_temp  )
  );
  Mux_2x1_NBits #(
    .Bits(17)
  )
  Mux_2x1_NBits_i2 (
    .sel( \glbl-reset  ),
    .in_0( s4 ),
    .in_1( 17'b0 ),
    .out( s5 )
  );
  assign \accum-class-score  = \accum-class-score_temp ;
endmodule

module \4-channel-IAE  (
  input \glbl-loop-clk ,
  input \glbl-inference-state ,
  input \enable-bit_(1bit) ,
  input [7:0] \WEIGHT-0 ,
  input [7:0] \WEIGHT-1 ,
  input [7:0] \WEIGHT-2 ,
  input [7:0] \WEIGHT-3 ,
  input \glbl-reset ,
  output [16:0] \accum-class-score-0 ,
  output [16:0] \accum-class-score-1 ,
  output [16:0] \accum-class-score-2 ,
  output [16:0] \accum-class-score-3 
);
  // IAE-0
  single_channel_IAE single_channel_IAE_i0 (
    .\enable-bit_(1bit) ( \enable-bit_(1bit)  ),
    .WEIGHT( \WEIGHT-0  ),
    .\glbl-loop-clk ( \glbl-loop-clk  ),
    .\glbl-inference-state ( \glbl-inference-state  ),
    .\glbl-reset ( \glbl-reset  ),
    .\accum-class-score ( \accum-class-score-0  )
  );
  // IAE-1
  single_channel_IAE single_channel_IAE_i1 (
    .\enable-bit_(1bit) ( \enable-bit_(1bit)  ),
    .WEIGHT( \WEIGHT-1  ),
    .\glbl-loop-clk ( \glbl-loop-clk  ),
    .\glbl-inference-state ( \glbl-inference-state  ),
    .\glbl-reset ( \glbl-reset  ),
    .\accum-class-score ( \accum-class-score-1  )
  );
  // IAE-2
  single_channel_IAE single_channel_IAE_i2 (
    .\enable-bit_(1bit) ( \enable-bit_(1bit)  ),
    .WEIGHT( \WEIGHT-2  ),
    .\glbl-loop-clk ( \glbl-loop-clk  ),
    .\glbl-inference-state ( \glbl-inference-state  ),
    .\glbl-reset ( \glbl-reset  ),
    .\accum-class-score ( \accum-class-score-2  )
  );
  // IAE-3
  single_channel_IAE single_channel_IAE_i3 (
    .\enable-bit_(1bit) ( \enable-bit_(1bit)  ),
    .WEIGHT( \WEIGHT-3  ),
    .\glbl-loop-clk ( \glbl-loop-clk  ),
    .\glbl-inference-state ( \glbl-inference-state  ),
    .\glbl-reset ( \glbl-reset  ),
    .\accum-class-score ( \accum-class-score-3  )
  );
endmodule
