/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module \4bit-PRNG  (
  input clk,
  input \glbl-boot ,
  output [1:0] var
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  assign s0 = (s5 ^ (s6 | \glbl-boot ));
  assign s2 = (s1 | \glbl-boot );
  assign s4 = (s3 | \glbl-boot );
  DIG_D_FF_1bit #(
    .Default(1)
  )
  DIG_D_FF_1bit_i0 (
    .D( s0 ),
    .C( clk ),
    .Q( s1 )
  );
  DIG_D_FF_1bit #(
    .Default(1)
  )
  DIG_D_FF_1bit_i1 (
    .D( s2 ),
    .C( clk ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s4 ),
    .C( clk ),
    .Q( s5 )
  );
  assign var[0] = s2;
  assign var[1] = s4;
  DIG_D_FF_1bit #(
    .Default(1)
  )
  DIG_D_FF_1bit_i3 (
    .D( s5 ),
    .C( clk ),
    .Q( s6 )
  );
endmodule
