/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_ROM_512X4_lownibblerom (
    input [8:0] A,
    input sel,
    output reg [3:0] D
);
    reg [3:0] my_rom [0:-1];

    always @ (*) begin
        if (~sel)
            D = 4'hz;
        else if (A > 9'hffffffffffffffff)
            D = 4'h0;
        else
            D = my_rom[A];
    end

    initial begin
    end
endmodule

module DIG_ROM_512X4_highnibblerom (
    input [8:0] A,
    input sel,
    output reg [3:0] D
);
    reg [3:0] my_rom [0:-1];

    always @ (*) begin
        if (~sel)
            D = 4'hz;
        else if (A > 9'hffffffffffffffff)
            D = 4'h0;
        else
            D = my_rom[A];
    end

    initial begin
    end
endmodule


module weight_bank_8bit (
  input [8:0] \loop-cnt-addr ,
  output [7:0] \class-weight 
);
  wire [3:0] s0;
  wire [3:0] s1;
  // low-nibble-rom
  DIG_ROM_512X4_lownibblerom DIG_ROM_512X4_lownibblerom_i0 (
    .A( \loop-cnt-addr  ),
    .sel( 1'b1 ),
    .D( s0 )
  );
  // high-nibble-rom
  DIG_ROM_512X4_highnibblerom DIG_ROM_512X4_highnibblerom_i1 (
    .A( \loop-cnt-addr  ),
    .sel( 1'b1 ),
    .D( s1 )
  );
  assign \class-weight [3:0] = s0;
  assign \class-weight [7:4] = s1;
endmodule

module \full-weight-ROM  (
  input [8:0] \loop-cnt-addr ,
  output [7:0] \class0-weight ,
  output [7:0] \class1-weight ,
  output [7:0] \class2-weight ,
  output [7:0] \class3-weight 
);
  // inform-bank
  weight_bank_8bit weight_bank_8bit_i0 (
    .\loop-cnt-addr ( \loop-cnt-addr  ),
    .\class-weight ( \class0-weight  )
  );
  // question-bank
  weight_bank_8bit weight_bank_8bit_i1 (
    .\loop-cnt-addr ( \loop-cnt-addr  ),
    .\class-weight ( \class1-weight  )
  );
  // directive-bank
  weight_bank_8bit weight_bank_8bit_i2 (
    .\loop-cnt-addr ( \loop-cnt-addr  ),
    .\class-weight ( \class2-weight  )
  );
  // commissive-bank
  weight_bank_8bit weight_bank_8bit_i3 (
    .\loop-cnt-addr ( \loop-cnt-addr  ),
    .\class-weight ( \class3-weight  )
  );
endmodule
