/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule

module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module RS_ff_as (
  input R,
  input S,
  output Q,
  output \Q' 
);
  wire Q_temp;
  wire \Q'_temp ;
  assign Q_temp = ~ (R | \Q'_temp );
  assign \Q'_temp  = ~ (Q_temp | S);
  assign Q = Q_temp;
  assign \Q'  = \Q'_temp ;
endmodule

module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule


module \keyboard-buffer  (
  input [4:0] \char-in ,
  input \char-valid ,
  input \glbl-rst ,
  output [4:0] \hash-char-out ,
  output \hash-char-strobe ,
  output \word-flush ,
  output \punct-q ,
  output \punct-excl ,
  output \punct-long ,
  output \user-submit 
);
  wire [4:0] \hash-char-out_temp ;
  wire \hash-char-strobe_temp ;
  wire \word-flush_temp ;
  wire \punct-q_temp ;
  wire \punct-excl_temp ;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire [3:0] s4;
  // char-reg
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i0 (
    .D( \char-in  ),
    .C( \char-valid  ),
    .en( 1'b1 ),
    .Q( \hash-char-out_temp  )
  );
  // is-submit
  CompUnsigned #(
    .Bits(5)
  )
  CompUnsigned_i1 (
    .a( \char-in  ),
    .b( 5'b11111 ),
    .\= ( s1 )
  );
  // is-space
  CompUnsigned #(
    .Bits(5)
  )
  CompUnsigned_i2 (
    .a( \hash-char-out_temp  ),
    .b( 5'b11010 ),
    .\= ( s0 )
  );
  // is-q
  CompUnsigned #(
    .Bits(5)
  )
  CompUnsigned_i3 (
    .a( \hash-char-out_temp  ),
    .b( 5'b11011 ),
    .\= ( \punct-q_temp  )
  );
  // is-excl
  CompUnsigned #(
    .Bits(5)
  )
  CompUnsigned_i4 (
    .a( \hash-char-out_temp  ),
    .b( 5'b11100 ),
    .\= ( \punct-excl_temp  )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s1 ),
    .C( \char-valid  ),
    .Q( \user-submit  )
  );
  assign \hash-char-strobe_temp  = (\char-valid  & ~ (s0 | \punct-q_temp  | \punct-excl_temp  | s1));
  RS_ff_as RS_ff_as_i6 (
    .R( s2 ),
    .S( \hash-char-strobe_temp  ),
    .Q( s3 )
  );
  assign \word-flush_temp  = (s3 & (s0 | s1));
  assign s2 = (\glbl-rst  | \word-flush_temp );
  // word-len
  DIG_Counter_Nbit #(
    .Bits(4)
  )
  DIG_Counter_Nbit_i7 (
    .en( 1'b1 ),
    .C( \word-flush_temp  ),
    .clr( \glbl-rst  ),
    .out( s4 )
  );
  // bigger-than-8
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i8 (
    .a( s4 ),
    .b( 4'b1000 ),
    .\> ( \punct-long  )
  );
  assign \hash-char-out  = \hash-char-out_temp ;
  assign \hash-char-strobe  = \hash-char-strobe_temp ;
  assign \word-flush  = \word-flush_temp ;
  assign \punct-q  = \punct-q_temp ;
  assign \punct-excl  = \punct-excl_temp ;
endmodule
