/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module \4bit_PRNG  (
  input clk,
  input \glbl-boot ,
  output [1:0] var
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  assign s0 = (s5 ^ (s6 | \glbl-boot ));
  assign s2 = (s1 | \glbl-boot );
  assign s4 = (s3 | \glbl-boot );
  DIG_D_FF_1bit #(
    .Default(1)
  )
  DIG_D_FF_1bit_i0 (
    .D( s0 ),
    .C( clk ),
    .Q( s1 )
  );
  DIG_D_FF_1bit #(
    .Default(1)
  )
  DIG_D_FF_1bit_i1 (
    .D( s2 ),
    .C( clk ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s4 ),
    .C( clk ),
    .Q( s5 )
  );
  assign var[0] = s2;
  assign var[1] = s4;
  DIG_D_FF_1bit #(
    .Default(1)
  )
  DIG_D_FF_1bit_i3 (
    .D( s5 ),
    .C( clk ),
    .Q( s6 )
  );
endmodule
module DIG_D_FF_Nbit
#(
    parameter Bits = 2,
    parameter Default = 0
)
(
   input [(Bits-1):0] D,
   input C,
   output [(Bits-1):0] Q,
   output [(Bits-1):0] \~Q
);
    reg [(Bits-1):0] state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module rnd_response_addr (
  input [1:0] \w-id ,
  input [1:0] rnd,
  input \argmax-fin ,
  output [3:0] \rsp-addr 
);
  wire [1:0] s0;
  wire [1:0] s1;
  DIG_D_FF_Nbit #(
    .Bits(2),
    .Default(0)
  )
  DIG_D_FF_Nbit_i0 (
    .D( rnd ),
    .C( \argmax-fin  ),
    .Q( s0 )
  );
  DIG_D_FF_Nbit #(
    .Bits(2),
    .Default(0)
  )
  DIG_D_FF_Nbit_i1 (
    .D( s0 ),
    .C( \argmax-fin  ),
    .Q( s1 )
  );
  assign \rsp-addr [1:0] = s1;
  assign \rsp-addr [3:2] = \w-id ;
endmodule

module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule

module DIG_ROM_256X5_n5bitROMw256addr (
    input [7:0] A,
    input sel,
    output reg [4:0] D
);
    reg [4:0] my_rom [0:255];

    always @ (*) begin
        if (~sel)
            D = 5'hz;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 5'hd;
        my_rom[1] = 5'he;
        my_rom[2] = 5'h13;
        my_rom[3] = 5'h4;
        my_rom[4] = 5'h3;
        my_rom[5] = 5'h1a;
        my_rom[6] = 5'h1a;
        my_rom[7] = 5'h1a;
        my_rom[8] = 5'h1a;
        my_rom[9] = 5'h1a;
        my_rom[10] = 5'h1a;
        my_rom[11] = 5'h1a;
        my_rom[12] = 5'h1a;
        my_rom[13] = 5'h1f;
        my_rom[14] = 5'h1f;
        my_rom[15] = 5'h1f;
        my_rom[16] = 5'h8;
        my_rom[17] = 5'h1a;
        my_rom[18] = 5'h12;
        my_rom[19] = 5'h4;
        my_rom[20] = 5'h4;
        my_rom[21] = 5'h1a;
        my_rom[22] = 5'h1a;
        my_rom[23] = 5'h1a;
        my_rom[24] = 5'h1a;
        my_rom[25] = 5'h1a;
        my_rom[26] = 5'h1a;
        my_rom[27] = 5'h1a;
        my_rom[28] = 5'h1a;
        my_rom[29] = 5'h1f;
        my_rom[30] = 5'h1f;
        my_rom[31] = 5'h1f;
        my_rom[32] = 5'h14;
        my_rom[33] = 5'hd;
        my_rom[34] = 5'h3;
        my_rom[35] = 5'h4;
        my_rom[36] = 5'h11;
        my_rom[37] = 5'h12;
        my_rom[38] = 5'h13;
        my_rom[39] = 5'he;
        my_rom[40] = 5'he;
        my_rom[41] = 5'h3;
        my_rom[42] = 5'h1a;
        my_rom[43] = 5'h1a;
        my_rom[44] = 5'h1a;
        my_rom[45] = 5'h1f;
        my_rom[46] = 5'h1f;
        my_rom[47] = 5'h1f;
        my_rom[48] = 5'h1;
        my_rom[49] = 5'he;
        my_rom[50] = 5'h11;
        my_rom[51] = 5'h8;
        my_rom[52] = 5'hd;
        my_rom[53] = 5'h6;
        my_rom[54] = 5'h1a;
        my_rom[55] = 5'h1a;
        my_rom[56] = 5'h1a;
        my_rom[57] = 5'h1a;
        my_rom[58] = 5'h1a;
        my_rom[59] = 5'h1a;
        my_rom[60] = 5'h1a;
        my_rom[61] = 5'h1f;
        my_rom[62] = 5'h1f;
        my_rom[63] = 5'h1f;
        my_rom[64] = 5'h6;
        my_rom[65] = 5'he;
        my_rom[66] = 5'he;
        my_rom[67] = 5'h3;
        my_rom[68] = 5'h1a;
        my_rom[69] = 5'h10;
        my_rom[70] = 5'h14;
        my_rom[71] = 5'h4;
        my_rom[72] = 5'h12;
        my_rom[73] = 5'h13;
        my_rom[74] = 5'h8;
        my_rom[75] = 5'he;
        my_rom[76] = 5'hd;
        my_rom[77] = 5'h1f;
        my_rom[78] = 5'h1f;
        my_rom[79] = 5'h1f;
        my_rom[80] = 5'hb;
        my_rom[81] = 5'h4;
        my_rom[82] = 5'h13;
        my_rom[83] = 5'h1a;
        my_rom[84] = 5'hc;
        my_rom[85] = 5'h4;
        my_rom[86] = 5'h1a;
        my_rom[87] = 5'h13;
        my_rom[88] = 5'h7;
        my_rom[89] = 5'h8;
        my_rom[90] = 5'hd;
        my_rom[91] = 5'ha;
        my_rom[92] = 5'h1a;
        my_rom[93] = 5'h1f;
        my_rom[94] = 5'h1f;
        my_rom[95] = 5'h1f;
        my_rom[96] = 5'h13;
        my_rom[97] = 5'h4;
        my_rom[98] = 5'hb;
        my_rom[99] = 5'hb;
        my_rom[100] = 5'h1a;
        my_rom[101] = 5'hc;
        my_rom[102] = 5'h4;
        my_rom[103] = 5'h1a;
        my_rom[104] = 5'hc;
        my_rom[105] = 5'he;
        my_rom[106] = 5'h11;
        my_rom[107] = 5'h4;
        my_rom[108] = 5'h1a;
        my_rom[109] = 5'h1f;
        my_rom[110] = 5'h1f;
        my_rom[111] = 5'h1f;
        my_rom[112] = 5'h16;
        my_rom[113] = 5'h7;
        my_rom[114] = 5'h18;
        my_rom[115] = 5'h1a;
        my_rom[116] = 5'h0;
        my_rom[117] = 5'h12;
        my_rom[118] = 5'ha;
        my_rom[119] = 5'h1a;
        my_rom[120] = 5'hc;
        my_rom[121] = 5'h4;
        my_rom[122] = 5'h1a;
        my_rom[123] = 5'h1a;
        my_rom[124] = 5'h1a;
        my_rom[125] = 5'h1f;
        my_rom[126] = 5'h1f;
        my_rom[127] = 5'h1f;
        my_rom[128] = 5'h8;
        my_rom[129] = 5'h1a;
        my_rom[130] = 5'h16;
        my_rom[131] = 5'h8;
        my_rom[132] = 5'hb;
        my_rom[133] = 5'hb;
        my_rom[134] = 5'h1a;
        my_rom[135] = 5'h13;
        my_rom[136] = 5'h11;
        my_rom[137] = 5'h18;
        my_rom[138] = 5'h1a;
        my_rom[139] = 5'h1a;
        my_rom[140] = 5'h1a;
        my_rom[141] = 5'h1f;
        my_rom[142] = 5'h1f;
        my_rom[143] = 5'h1f;
        my_rom[144] = 5'h2;
        my_rom[145] = 5'h4;
        my_rom[146] = 5'h11;
        my_rom[147] = 5'h13;
        my_rom[148] = 5'h0;
        my_rom[149] = 5'h8;
        my_rom[150] = 5'hd;
        my_rom[151] = 5'hb;
        my_rom[152] = 5'h18;
        my_rom[153] = 5'h1a;
        my_rom[154] = 5'h1a;
        my_rom[155] = 5'h1a;
        my_rom[156] = 5'h1a;
        my_rom[157] = 5'h1f;
        my_rom[158] = 5'h1f;
        my_rom[159] = 5'h1f;
        my_rom[160] = 5'he;
        my_rom[161] = 5'hd;
        my_rom[162] = 5'h1a;
        my_rom[163] = 5'h8;
        my_rom[164] = 5'h13;
        my_rom[165] = 5'h1a;
        my_rom[166] = 5'h1a;
        my_rom[167] = 5'h1a;
        my_rom[168] = 5'h1a;
        my_rom[169] = 5'h1a;
        my_rom[170] = 5'h1a;
        my_rom[171] = 5'h1a;
        my_rom[172] = 5'h1a;
        my_rom[173] = 5'h1f;
        my_rom[174] = 5'h1f;
        my_rom[175] = 5'h1f;
        my_rom[176] = 5'hd;
        my_rom[177] = 5'he;
        my_rom[178] = 5'h1a;
        my_rom[179] = 5'h16;
        my_rom[180] = 5'h0;
        my_rom[181] = 5'h18;
        my_rom[182] = 5'h1a;
        my_rom[183] = 5'h1a;
        my_rom[184] = 5'h1a;
        my_rom[185] = 5'h1a;
        my_rom[186] = 5'h1a;
        my_rom[187] = 5'h1a;
        my_rom[188] = 5'h1a;
        my_rom[189] = 5'h1f;
        my_rom[190] = 5'h1f;
        my_rom[191] = 5'h1f;
        my_rom[192] = 5'h0;
        my_rom[193] = 5'h6;
        my_rom[194] = 5'h11;
        my_rom[195] = 5'h4;
        my_rom[196] = 5'h4;
        my_rom[197] = 5'h3;
        my_rom[198] = 5'h1a;
        my_rom[199] = 5'h1a;
        my_rom[200] = 5'h1a;
        my_rom[201] = 5'h1a;
        my_rom[202] = 5'h1a;
        my_rom[203] = 5'h1a;
        my_rom[204] = 5'h1a;
        my_rom[205] = 5'h1f;
        my_rom[206] = 5'h1f;
        my_rom[207] = 5'h1f;
        my_rom[208] = 5'h12;
        my_rom[209] = 5'he;
        my_rom[210] = 5'h14;
        my_rom[211] = 5'hd;
        my_rom[212] = 5'h3;
        my_rom[213] = 5'h12;
        my_rom[214] = 5'h1a;
        my_rom[215] = 5'h6;
        my_rom[216] = 5'he;
        my_rom[217] = 5'he;
        my_rom[218] = 5'h3;
        my_rom[219] = 5'h1a;
        my_rom[220] = 5'h1a;
        my_rom[221] = 5'h1f;
        my_rom[222] = 5'h1f;
        my_rom[223] = 5'h1f;
        my_rom[224] = 5'hb;
        my_rom[225] = 5'h4;
        my_rom[226] = 5'h13;
        my_rom[227] = 5'h12;
        my_rom[228] = 5'h1a;
        my_rom[229] = 5'h3;
        my_rom[230] = 5'he;
        my_rom[231] = 5'h1a;
        my_rom[232] = 5'h8;
        my_rom[233] = 5'h13;
        my_rom[234] = 5'h1a;
        my_rom[235] = 5'h1a;
        my_rom[236] = 5'h1a;
        my_rom[237] = 5'h1f;
        my_rom[238] = 5'h1f;
        my_rom[239] = 5'h1f;
        my_rom[240] = 5'h8;
        my_rom[241] = 5'h1a;
        my_rom[242] = 5'h11;
        my_rom[243] = 5'h4;
        my_rom[244] = 5'h5;
        my_rom[245] = 5'h14;
        my_rom[246] = 5'h12;
        my_rom[247] = 5'h4;
        my_rom[248] = 5'h1a;
        my_rom[249] = 5'h1a;
        my_rom[250] = 5'h1a;
        my_rom[251] = 5'h1a;
        my_rom[252] = 5'h1a;
        my_rom[253] = 5'h1f;
        my_rom[254] = 5'h1f;
        my_rom[255] = 5'h1f;
    end
endmodule


module stream_response_char (
  input [3:0] \rsp-addr ,
  input \stream-clk ,
  input \print-enable ,
  input \glbl-boot ,
  output [4:0] \char-output 
);
  wire s0;
  wire [3:0] s1;
  wire [7:0] s2;
  // 13char-4bitcnt
  DIG_Counter_Nbit #(
    .Bits(4)
  )
  DIG_Counter_Nbit_i0 (
    .en( \print-enable  ),
    .C( \stream-clk  ),
    .clr( s0 ),
    .out( s1 )
  );
  assign s0 = (\glbl-boot  | (s1[0] & s1[2] & s1[3]));
  // 5bitROM-w-256addr
  DIG_ROM_256X5_n5bitROMw256addr DIG_ROM_256X5_n5bitROMw256addr_i1 (
    .A( s2 ),
    .sel( \print-enable  ),
    .D( \char-output  )
  );
  assign s2[3:0] = s1;
  assign s2[7:4] = \rsp-addr ;
endmodule

module \output-gen  (
  input \glbl-boot ,
  input [1:0] \w-id ,
  input \argmax-fin ,
  input \lfsr-clk ,
  input \print-enable ,
  input \stream-clk ,
  output [4:0] \char-stream 
);
  wire [3:0] s0;
  wire [1:0] s1;
  \4bit_PRNG  \4bit_PRNG_i0 (
    .clk( \lfsr-clk  ),
    .\glbl-boot ( \glbl-boot  ),
    .var( s1 )
  );
  rnd_response_addr rnd_response_addr_i1 (
    .\w-id ( \w-id  ),
    .rnd( s1 ),
    .\argmax-fin ( \argmax-fin  ),
    .\rsp-addr ( s0 )
  );
  stream_response_char stream_response_char_i2 (
    .\rsp-addr ( s0 ),
    .\stream-clk ( \stream-clk  ),
    .\print-enable ( \print-enable  ),
    .\glbl-boot ( \glbl-boot  ),
    .\char-output ( \char-stream  )
  );
endmodule
