/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_Nbit
#(
    parameter Bits = 2,
    parameter Default = 0
)
(
   input [(Bits-1):0] D,
   input C,
   output [(Bits-1):0] Q,
   output [(Bits-1):0] \~Q
);
    reg [(Bits-1):0] state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module \rnd-response-addr  (
  input [1:0] \w-id ,
  input [1:0] rnd,
  input \argmax-fin ,
  output [3:0] \rsp-addr 
);
  wire [1:0] s0;
  wire [1:0] s1;
  DIG_D_FF_Nbit #(
    .Bits(2),
    .Default(0)
  )
  DIG_D_FF_Nbit_i0 (
    .D( rnd ),
    .C( \argmax-fin  ),
    .Q( s0 )
  );
  DIG_D_FF_Nbit #(
    .Bits(2),
    .Default(0)
  )
  DIG_D_FF_Nbit_i1 (
    .D( s0 ),
    .C( \argmax-fin  ),
    .Q( s1 )
  );
  assign \rsp-addr [1:0] = s1;
  assign \rsp-addr [3:2] = \w-id ;
endmodule
