/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module \RS-ff-as  (
  input R,
  input S,
  output Q,
  output \Q' 
);
  wire Q_temp;
  wire \Q'_temp ;
  assign Q_temp = ~ (R | \Q'_temp );
  assign \Q'_temp  = ~ (Q_temp | S);
  assign Q = Q_temp;
  assign \Q'  = \Q'_temp ;
endmodule
