/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module \single-channel-IAE  (
  input \enable-bit_(1bit) ,
  input [7:0] WEIGHT,
  input \glbl-loop-clk ,
  input \glbl-inference-state ,
  output [16:0] \accum._class_score 
);
  wire [7:0] s0;
  wire [7:0] s1;
  wire s2;
  wire [16:0] s3;
  wire [16:0] \accum._class_score_temp ;
  wire [16:0] s4;
  assign s0[0] = \enable-bit_(1bit) ;
  assign s0[1] = \enable-bit_(1bit) ;
  assign s0[2] = \enable-bit_(1bit) ;
  assign s0[3] = \enable-bit_(1bit) ;
  assign s0[4] = \enable-bit_(1bit) ;
  assign s0[5] = \enable-bit_(1bit) ;
  assign s0[6] = \enable-bit_(1bit) ;
  assign s0[7] = \enable-bit_(1bit) ;
  assign s1 = (s0 & WEIGHT);
  assign s2 = s1[7];
  assign s3[7:0] = s1;
  assign s3[8] = s2;
  assign s3[9] = s2;
  assign s3[10] = s2;
  assign s3[11] = s2;
  assign s3[12] = s2;
  assign s3[13] = s2;
  assign s3[14] = s2;
  assign s3[15] = s2;
  assign s3[16] = s2;
  // 17bit RCA
  DIG_Add #(
    .Bits(17)
  )
  DIG_Add_i0 (
    .a( s3 ),
    .b( \accum._class_score_temp  ),
    .c_i( 1'b0 ),
    .s( s4 )
  );
  // 17bit accum. reg.
  DIG_Register_BUS #(
    .Bits(17)
  )
  DIG_Register_BUS_i1 (
    .D( s4 ),
    .C( \glbl-loop-clk  ),
    .en( \glbl-inference-state  ),
    .Q( \accum._class_score_temp  )
  );
  assign \accum._class_score  = \accum._class_score_temp ;
endmodule
