/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module \single-trial  (
  input [16:0] A,
  input [16:0] B,
  input [1:0] id_A,
  input [1:0] id_B,
  output [16:0] win,
  output [1:0] \w-id 
);
  wire [16:0] s0;
  wire [16:0] s1;
  wire s2;
  assign s0 = ~ B;
  // 17bit adder
  DIG_Add #(
    .Bits(17)
  )
  DIG_Add_i0 (
    .a( A ),
    .b( s0 ),
    .c_i( 1'b1 ),
    .s( s1 )
  );
  assign s2 = ~ s1[16];
  Mux_2x1_NBits #(
    .Bits(17)
  )
  Mux_2x1_NBits_i1 (
    .sel( s2 ),
    .in_0( B ),
    .in_1( A ),
    .out( win )
  );
  Mux_2x1_NBits #(
    .Bits(2)
  )
  Mux_2x1_NBits_i2 (
    .sel( s2 ),
    .in_0( id_B ),
    .in_1( id_A ),
    .out( \w-id  )
  );
endmodule
