/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module \sticky-reg-bank-64bit  (
  input [63:0] \dec-word-in ,
  input \word-flush ,
  input \master-reset ,
  output [63:0] presence
);
  wire [63:0] s0;
  wire [63:0] presence_temp;
  wire [63:0] s1;
  // REG_64
  DIG_Register_BUS #(
    .Bits(64)
  )
  DIG_Register_BUS_i0 (
    .D( s0 ),
    .C( \word-flush  ),
    .en( 1'b1 ),
    .Q( presence_temp )
  );
  assign s1 = (presence_temp | \dec-word-in );
  Mux_2x1_NBits #(
    .Bits(64)
  )
  Mux_2x1_NBits_i1 (
    .sel( \master-reset  ),
    .in_0( s1 ),
    .in_1( 64'b0 ),
    .out( s0 )
  );
  assign presence = presence_temp;
endmodule
