/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module \token-hasher  (
  input [4:0] \hash-char-in ,
  input \hash-char-strobe ,
  input \word-flush ,
  input \glbl-rst ,
  output [7:0] \word-hash-addr 
);
  wire [7:0] \word-hash-addr_temp ;
  wire [7:0] s0;
  wire [7:0] s1;
  wire [7:0] s2;
  wire [7:0] s3;
  wire s4;
  assign s2[4:0] = \hash-char-in ;
  assign s2[7:5] = 3'b0;
  assign s4 = (\word-flush  | \glbl-rst );
  // hash-reg
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i0 (
    .D( s0 ),
    .C( \hash-char-strobe  ),
    .en( 1'b1 ),
    .Q( \word-hash-addr_temp  )
  );
  assign s3 = (s2 ^ s1);
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i1 (
    .sel( s4 ),
    .in_0( s3 ),
    .in_1( 8'b0 ),
    .out( s0 )
  );
  assign s1[0] = \word-hash-addr_temp [7];
  assign s1[1] = \word-hash-addr_temp [6];
  assign s1[2] = \word-hash-addr_temp [5];
  assign s1[3] = \word-hash-addr_temp [4];
  assign s1[4] = \word-hash-addr_temp [3];
  assign s1[5] = \word-hash-addr_temp [2];
  assign s1[6] = \word-hash-addr_temp [1];
  assign s1[7] = \word-hash-addr_temp [0];
  assign \word-hash-addr  = \word-hash-addr_temp ;
endmodule
