/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule

module LUT_StateLUT (
    input \0 ,
    input \1 ,
    input \2 ,
    input \3 ,
    input \4 ,
    output reg  [1:0]  out
);
    reg [1:0] my_lut [0:31];
    wire [4:0] temp;
    assign temp = {\4 , \3 , \2 , \1 , \0 };

    always @ (*) begin
       out = my_lut[temp];
    end

    initial begin
        my_lut[0] = 2'h0;
        my_lut[1] = 2'h1;
        my_lut[2] = 2'h2;
        my_lut[3] = 2'h0;
        my_lut[4] = 2'h1;
        my_lut[5] = 2'h1;
        my_lut[6] = 2'h2;
        my_lut[7] = 2'h0;
        my_lut[8] = 2'h0;
        my_lut[9] = 2'h2;
        my_lut[10] = 2'h2;
        my_lut[11] = 2'h0;
        my_lut[12] = 2'h0;
        my_lut[13] = 2'h2;
        my_lut[14] = 2'h0;
        my_lut[15] = 2'h0;
        my_lut[16] = 2'h0;
        my_lut[17] = 2'h1;
        my_lut[18] = 2'h0;
        my_lut[19] = 2'h0;
        my_lut[20] = 2'h0;
        my_lut[21] = 2'h0;
        my_lut[22] = 2'h0;
        my_lut[23] = 2'h0;
        my_lut[24] = 2'h0;
        my_lut[25] = 2'h0;
        my_lut[26] = 2'h0;
        my_lut[27] = 2'h0;
        my_lut[28] = 2'h0;
        my_lut[29] = 2'h0;
        my_lut[30] = 2'h0;
        my_lut[31] = 2'h0;
    end
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module \universal-controller  (
  input \clk-master ,
  input \SYS-BOOT , // open sesame
  input \glbl-rst ,
  input \user-submit ,
  input \print-done ,
  output [1:0] \glbl-state ,
  output \inference-en ,
  output \argmax-fin ,
  output \run-printer ,
  output [8:0] \loop-cnt-adder ,
  output \clk-lfsr ,
  output \clk-loop ,
  output \clk-printer 
);
  wire [1:0] \glbl-state_temp ;
  wire \inference-en_temp ;
  wire \argmax-fin_temp ;
  wire \run-printer_temp ;
  wire [8:0] \loop-cnt-adder_temp ;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire [1:0] s4;
  wire [1:0] s5;
  wire s6;
  wire s7;
  wire s8;
  wire [9:0] s9;
  assign s0 = (\glbl-rst  | \user-submit );
  assign s6 = (\SYS-BOOT  | \glbl-rst );
  // 9bit-loop-counter
  DIG_Counter_Nbit #(
    .Bits(9)
  )
  DIG_Counter_Nbit_i0 (
    .en( \inference-en_temp  ),
    .C( \clk-master  ),
    .clr( s0 ),
    .out( \loop-cnt-adder_temp  )
  );
  // StateLUT
  LUT_StateLUT LUT_StateLUT_i1 (
    .\0 ( s2 ),
    .\1 ( s3 ),
    .\2 ( \user-submit  ),
    .\3 ( s1 ),
    .\4 ( \print-done  ),
    .out( s4 )
  );
  Mux_2x1_NBits #(
    .Bits(2)
  )
  Mux_2x1_NBits_i2 (
    .sel( s6 ),
    .in_0( s4 ),
    .in_1( 2'b0 ),
    .out( s5 )
  );
  // is-it-259
  CompUnsigned #(
    .Bits(9)
  )
  CompUnsigned_i3 (
    .a( \loop-cnt-adder_temp  ),
    .b( 9'b100000011 ),
    .\= ( s1 )
  );
  // state-tracker
  DIG_Register_BUS #(
    .Bits(2)
  )
  DIG_Register_BUS_i4 (
    .D( s5 ),
    .C( \clk-master  ),
    .en( 1'b1 ),
    .Q( \glbl-state_temp  )
  );
  assign s2 = \glbl-state_temp [0];
  assign s3 = \glbl-state_temp [1];
  assign s7 = \glbl-state_temp [0];
  assign \argmax-fin_temp  = \glbl-state_temp [1];
  assign \inference-en_temp  = (s7 & ~ \argmax-fin_temp );
  assign \run-printer_temp  = (~ s7 & \argmax-fin_temp );
  assign \clk-printer  = (\run-printer_temp  & s8);
  // clk-prescaler-cnt
  DIG_Counter_Nbit #(
    .Bits(10)
  )
  DIG_Counter_Nbit_i5 (
    .en( 1'b1 ),
    .C( \clk-master  ),
    .clr( s8 ),
    .out( s9 )
  );
  // clk-prescaler-cmpr
  CompUnsigned #(
    .Bits(10)
  )
  CompUnsigned_i6 (
    .a( s9 ),
    .b( 10'b10100 ),
    .\= ( s8 )
  );
  assign \glbl-state  = \glbl-state_temp ;
  assign \inference-en  = \inference-en_temp ;
  assign \argmax-fin  = \argmax-fin_temp ;
  assign \run-printer  = \run-printer_temp ;
  assign \loop-cnt-adder  = \loop-cnt-adder_temp ;
  assign \clk-lfsr  = \clk-master ;
  assign \clk-loop  = \clk-master ;
endmodule
